### ISSUE TITLE
Understanding odds

### ISSUE THREAD

**Issue by squibsy** [se1exin/split#1]
This is nifty, but I don't understand  how the odds work. I'm used to seeing "4 to 1", so I don't get the 51s and 101s listed http://www.races.com.au/melbourne-cup/melbourne-cup-odds/ - are these actually saying  51-1 and 101-1 odds? Seems like this system will only work for large races with lots of long-odds runners? I've tried a few regular races and can't find a winning combo.

**Comment by se1exin** [comment]
Yes they are 51-1 and 101-1 odds. Please also note that this really shouldn't be taken too seriously or used to actually try and make money. Its more of a joke than anything. ..sorry
